# Generated by Django 5.1.7 on 2025-04-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='expenditure',
        ),
    ]
